"""
Task Executor - Execute web agent tasks using Playwright

This module provides the core execution engine for running tasks defined
in task_spec.json files. It uses Playwright to control the browser and
execute the steps defined in oracle traces or generated by an agent.
"""

import json
import time
import os
import sqlite3
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple
from urllib.parse import urlsplit, urlunsplit
from playwright.sync_api import sync_playwright, Page, Browser, BrowserContext
from runtime_paths import state_path as runtime_state_path

# Import our custom modules
from .assertions_dsl import AssertionDSL
from .error_handlers import (
    TimeoutHandler, NetworkErrorHandler, ElementNotFoundHandler,
    AssertionFailureHandler, check_preconditions, ErrorReport
)


def _should_log_debug() -> bool:
    value = os.environ.get("WEBAGENT_DEBUG_LOGS", "").strip().lower()
    return value in {"1", "true", "yes", "on"}


class ExecutionResult:
    """Result of a task execution"""

    def __init__(self, task_id: str):
        self.task_id = task_id
        self.success = False
        self.final_state = "pending"  # pending, running, completed, failed, aborted
        self.steps_completed = 0
        self.steps_total = 0
        self.time_elapsed = 0.0
        self.error = None
        self.trace = []
        self.memory_updates = {}
        self.artifacts = []
        self.warnings = []
        self.extracted_data = {}
        self.verification = {}

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization"""
        return {
            "task_id": self.task_id,
            "success": self.success,
            "final_state": self.final_state,
            "steps_completed": self.steps_completed,
            "steps_total": self.steps_total,
            "time_elapsed": self.time_elapsed,
            "error": self.error.to_dict() if self.error else None,
            "trace": self.trace,
            "memory_updates": self.memory_updates,
            "artifacts": self.artifacts,
            "warnings": self.warnings,
            "extracted_data": self.extracted_data,
            "verification": self.verification,
        }


class TaskExecutor:
    """Main task executor using Playwright"""

    SUITE_PORT = int(os.getenv("WEB_SUITE_PORT", "8014"))

    def __init__(
        self,
        database_path: str = "data.db",
        env_api_url: Optional[str] = None,
        headless: bool = False,
        slow_mo: int = 0
    ):
        """
        Initialize task executor

        Args:
            database_path: Path to SQLite database
            env_api_url: URL for environment API
            headless: Run browser in headless mode
            slow_mo: Slow down operations by N milliseconds
        """
        self.database_path = database_path
        self.env_api_url = env_api_url or f"http://localhost:{self.SUITE_PORT}/api/env"
        self.headless = headless
        self.slow_mo = slow_mo
        self.fast_mode = os.getenv("BENCHMARK_FAST_MODE", "false").lower() == "true"
        self.open_settle_sec = 0.5 if self.fast_mode else 2.0
        self.click_pause_sec = 0.1 if self.fast_mode else 0.5
        self.backend_settle_sec = 0.5 if self.fast_mode else 2.0

        # State
        self.memory = {}  # In-memory KV store
        self.browser: Optional[Browser] = None
        self.context: Optional[BrowserContext] = None
        self.page: Optional[Page] = None
        self._fallback_input_cursor = 0

        # Load memory from database
        self._load_memory()

    def _extract_has_text(self, selector: str) -> Optional[str]:
        """Extract :has-text('...') content from selector when present."""
        match = re.search(r":has-text\(([\"'])(.*?)\1\)", selector)
        if not match:
            return None
        value = match.group(2).strip()
        return value or None

    def _selector_tokens(self, selector: str) -> List[str]:
        """Tokenize selector for fuzzy fallback matching."""
        cleaned = re.sub(r"[^a-zA-Z0-9_\-\u4e00-\u9fff]+", " ", selector.lower())
        raw_tokens = re.split(r"[\s._#:\-\[\]\(\)]+", cleaned)
        stop = {"btn", "button", "input", "textarea", "select", "modal", "card", "item", "list", "pri", "lg", "sm"}
        return [t for t in raw_tokens if len(t) >= 2 and t not in stop]

    def _fallback_fill(self, selector: str, value: str) -> bool:
        """Fallback fill by fuzzy-matching visible fields."""
        fields = self.page.locator("input:visible, textarea:visible")
        count = fields.count()
        if count == 0:
            return False

        tokens = self._selector_tokens(selector)
        ranked = []

        for i in range(count):
            field = fields.nth(i)
            try:
                meta = " ".join([
                    field.get_attribute("id") or "",
                    field.get_attribute("name") or "",
                    field.get_attribute("placeholder") or "",
                    field.get_attribute("aria-label") or "",
                    field.get_attribute("type") or "",
                ]).lower()
                current = field.input_value()
            except Exception:
                meta = ""
                current = ""

            score = 0.0
            for token in tokens:
                if token in meta:
                    score += 2.0
            if not current:
                score += 1.0
            if i >= self._fallback_input_cursor:
                score += 0.2
            ranked.append((score, i))

        ranked.sort(reverse=True)

        for _, idx in ranked:
            try:
                fields.nth(idx).fill(value)
                self._fallback_input_cursor = idx + 1
                print(f"    ↪ Fallback type used: input[{idx}]")
                return True
            except Exception:
                continue
        return False

    def _fallback_select(self, selector: str, value: str) -> bool:
        """Fallback select by fuzzy-matching visible select elements."""
        selects = self.page.locator("select:visible")
        count = selects.count()
        if count == 0:
            return False

        tokens = self._selector_tokens(selector)
        ranked = []
        for i in range(count):
            sel = selects.nth(i)
            meta = " ".join([
                sel.get_attribute("id") or "",
                sel.get_attribute("name") or "",
                sel.get_attribute("aria-label") or "",
            ]).lower()
            score = 0.0
            for token in tokens:
                if token in meta:
                    score += 2.0
            ranked.append((score, i))
        ranked.sort(reverse=True)

        for _, idx in ranked:
            target = selects.nth(idx)
            try:
                target.select_option(value=value)
                print(f"    ↪ Fallback select used: select[{idx}]")
                return True
            except Exception:
                try:
                    options = target.locator("option")
                    if options.count() == 0:
                        continue
                    first_val = options.first.get_attribute("value")
                    target.select_option(value=first_val)
                    print(f"    ↪ Fallback select used: select[{idx}] first option")
                    return True
                except Exception:
                    continue
        return False

    def _load_memory(self):
        """Load memory from database with retry logic"""
        if not os.path.exists(self.database_path):
            print(f"⚠️  Database not found: {self.database_path}")
            return

        for attempt in range(5):
            try:
                conn = sqlite3.connect(self.database_path, timeout=10)
                cursor = conn.cursor()
                cursor.execute("SELECT key, value FROM memory_kv")

                for row in cursor.fetchall():
                    key, value = row
                    if 'courses.DL101.state' in key:
                        if _should_log_debug():
                            print(f"DEBUG: Loaded key {key} = {value}")
                    try:
                        self.memory[key] = json.loads(value)
                    except:
                        self.memory[key] = value

                conn.close()
                print(f"✅ Loaded {len(self.memory)} memory entries from database")
                return
            except sqlite3.OperationalError as e:
                if "locked" in str(e):
                    print(f"⚠️  Database locked loading memory, retrying ({attempt+1}/5)...")
                    time.sleep(1)
                else:
                    print(f"⚠️  Error loading memory: {e}")
                    return
            except Exception as e:
                print(f"⚠️  Error loading memory: {e}")
                return

    def _save_memory(self, key: str, value: Any, source: str, confidence: float = 1.0):
        """Save memory entry to database with retry logic"""
        if not os.path.exists(self.database_path):
            return

        for attempt in range(5):
            try:
                conn = sqlite3.connect(self.database_path, timeout=10)
                cursor = conn.cursor()

                # Serialize value to JSON
                value_json = json.dumps(value) if not isinstance(value, str) else value

                cursor.execute("""
                    INSERT OR REPLACE INTO memory_kv (key, value, ts, source, confidence)
                    VALUES (?, ?, ?, ?, ?)
                """, (key, value_json, datetime.utcnow().isoformat() + "Z", source, confidence))

                conn.commit()
                conn.close()

                # Update in-memory copy
                self.memory[key] = value
                return
            except sqlite3.OperationalError as e:
                if "locked" in str(e):
                    print(f"⚠️  Database locked saving memory, retrying ({attempt+1}/5)...")
                    time.sleep(1)
                else:
                    print(f"⚠️  Error saving memory: {e}")
                    return
            except Exception as e:
                print(f"⚠️  Error saving memory: {e}")
                return

    def _env_api(self, channel: str, path: str) -> Any:
        """Query environment API"""
        # TODO: Implement HTTP call to env API
        # For now, query database directly

        # Check JSON state first for new domains
        json_domains = (
            "health", "trips", "work", "expenses", "meters", "permits", "security", "payments",
            "contracts", "warranty", "courses", "invoices", "settlements", "autopay", "accounts",
            "finance", "food", "mobile", "identity", "support", "housing", "market", "cloud",
            "devices", "world_state", "library", "gov", "social", "charity", "supply_chain",
            "user_profile", "auctions", "tickets"
        )
        parts = path.split('.')
        
        if parts[0] in json_domains or parts[0] == 'market': # Explicitly reload for market due to nested structure
            if _should_log_debug():
                print(f"DEBUG: TaskExecutor._env_api reading from: {runtime_state_path()}")
            state_path = runtime_state_path()
            
            if state_path.exists():
                try:
                    current = json.loads(state_path.read_text(encoding='utf-8'))
                    for part in parts:
                        if isinstance(current, dict):
                            current = current.get(part)
                        elif isinstance(current, list):
                            try:
                                current = current[int(part)]
                            except (ValueError, IndexError):
                                return None
                        else:
                            return None
                        
                        if current is None:
                            if _should_log_debug():
                                print(f"DEBUG: _env_api traversal failed at part '{part}' for path '{path}'")
                            return None
                    if _should_log_debug():
                        print(f"DEBUG: _env_api found value: {current}")
                    return current
                except Exception:
                    pass

        if not os.path.exists(self.database_path):
            return None

        try:
            conn = sqlite3.connect(self.database_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()

            # Simple implementation: parse path like "orders.O-10001.state"
            # parts already split above

            if parts[0] == 'orders' and len(parts) >= 2:
                order_id = parts[1]
                if order_id == '*':
                    # Get most recent order
                    cursor.execute("SELECT * FROM orders ORDER BY created_at DESC LIMIT 1")
                else:
                    cursor.execute("SELECT * FROM orders WHERE id = ?", (order_id,))

                row = cursor.fetchone()
                if row and len(parts) >= 3:
                    field = parts[2]
                    result = row[field] if field in row.keys() else None
                    conn.close()
                    return result
                if row and len(parts) == 2 and parts[1] == '*':
                    conn.close()
                    return row['state']

            elif parts[0] == 'payments' and 'cards' in parts:
                # payments.cards.1234.state
                if len(parts) >= 4:
                    last4 = parts[2]
                    field = parts[3]
                    cursor.execute(f"SELECT {field} FROM cards WHERE last4 = ?", (last4,))
                    row = cursor.fetchone()
                    if row:
                        result = row[0]
                        conn.close()
                        return result

            elif parts[0] == 'accounts':
                # accounts.*.balance
                cursor.execute("SELECT * FROM accounts ORDER BY created_at DESC LIMIT 1")
                row = cursor.fetchone()
                if row and ('balance' in parts or parts[1] == '*'):
                    result = row['balance']
                    conn.close()
                    return result

            elif parts[0] == 'autopay':
                from pathlib import Path
                state_path = Path('env/state.json')
                if state_path.exists():
                    env_state = json.loads(state_path.read_text())
                    entries = env_state.get('autopay', {})
                    first = next(iter(entries.values()), None)
                    if first:
                        if len(parts) == 2 and parts[1] == '*':
                            conn.close()
                            return first
                        if len(parts) >= 3 and parts[1] == '*':
                            field = parts[2]
                            conn.close()
                            return first.get(field)

            conn.close()
            return None

        except Exception as e:
            print(f"⚠️  Error querying env API: {e}")
            return None

    def run(self, task_spec_path: str, oracle_trace_path: Optional[str] = None) -> ExecutionResult:
        """
        Execute a task

        Args:
            task_spec_path: Path to task_spec.json
            oracle_trace_path: Optional path to oracle_trace.json (for testing)

        Returns:
            ExecutionResult with execution details
        """
        if _should_log_debug():
            print(f"DEBUG: Loading task spec from: {task_spec_path}")
        # Load task spec
        with open(task_spec_path) as f:
            task_spec = json.load(f)

        task_id = task_spec['task_id']
        print(f"\n{'='*80}")
        print(f"🚀 Executing task: {task_id}")
        print(f"{'='*80}")

        result = ExecutionResult(task_id)
        start_time = time.time()

        try:
            # Check preconditions
            print("\n📋 Checking preconditions...")
            if _should_log_debug():
                print(f"DEBUG: Loaded preconditions: {task_spec.get('preconditions', [])}")
            self._check_preconditions(task_spec)
            print("✅ All preconditions met")

            # Initialize extraction storage
            self._extracted_data = {}

            # Load oracle trace if provided
            steps = None
            if oracle_trace_path:
                with open(oracle_trace_path) as f:
                    oracle_trace = json.load(f)
                    steps = oracle_trace.get('steps', [])
                    result.steps_total = len(steps)
                    print(f"📜 Loaded oracle trace with {len(steps)} steps")

            # Start browser
            print("\n🌐 Starting browser...")
            self._start_browser(task_spec)

            result.final_state = "running"

            # Execute steps
            if steps:
                print(f"\n⚡ Executing {len(steps)} steps...")
                for i, step in enumerate(steps):
                    print(f"\n  Step {i+1}/{len(steps)}: {step.get('act')} {step.get('note', '')}")

                    try:
                        self._execute_step(step, task_spec)
                        result.steps_completed = i + 1
                        result.trace.append(step)

                    except Exception as e:
                        print(f"    ❌ Step failed: {e}")
                        result.error = self._handle_step_error(e, step, task_spec, i)

                        if result.error and result.error.final_state == "aborted":
                            break

            # Settlement wait for backend async tasks
            print("\n⏳ Waiting for backend settlement...")
            time.sleep(self.backend_settle_sec)

            # Verify success criteria and required scoring checkpoints
            print("\n✓ Verifying success criteria + required checkpoints...")
            success = self._verify_success(task_spec)
            result.verification = dict(getattr(self, "_last_verification", {}) or {})

            if success:
                print("✅ Task completed successfully!")
                result.success = True
                result.final_state = "completed"

                # Update memory
                self._update_memory(task_spec)
            else:
                print("❌ Task failed: success criteria / required checkpoints not met")
                result.final_state = "failed"
            
            # Populate extracted data in result
            if hasattr(self, '_extracted_data'):
                result.extracted_data = self._extracted_data

        except Exception as e:
            print(f"\n❌ Task execution failed: {e}")
            result.final_state = "failed"
            result.error = ErrorReport(
                task_id=task_id,
                error_type="unknown",
                timestamp=datetime.utcnow().isoformat() + "Z",
                step_index=-1,
                error_message=str(e)
            )

        finally:
            # Cleanup
            result.time_elapsed = time.time() - start_time
            self._stop_browser()

        # Save result
        self._save_result(result)

        print(f"\n{'='*80}")
        print(f"📊 Execution completed in {result.time_elapsed:.2f}s")
        print(f"   Success: {result.success}")
        print(f"   Steps: {result.steps_completed}/{result.steps_total}")
        print(f"{'='*80}\n")

        return result

    def _check_preconditions(self, task_spec: Dict[str, Any]):
        """Check task preconditions"""
        preconditions = task_spec.get('preconditions', [])
        if _should_log_debug():
            print(f"DEBUG: TaskExecutor memory in preconditions check: health.insurance.active = {self.memory.get('health.insurance.active')}")

        if not preconditions:
            return

        # Create DSL evaluator
        dsl = AssertionDSL(None, self.memory, self._env_api)

        for precondition in preconditions:
            if "banking.balance" in precondition:
                 try:
                     val = self.memory.get("banking", {}).get("balance", {}).get("checking", "MISSING")
                 except:
                     val = "ERROR"
                 if _should_log_debug():
                     print(f"DEBUG: Checking {precondition}. Memory value: {val}")
            try:
                # For memory-only preconditions, we can evaluate without a page
                result = dsl.evaluate(precondition)
                if not result:
                    raise Exception(f"Precondition not met: {precondition}")
            except Exception as e:
                raise Exception(f"Precondition check failed: {precondition} - {e}")

    def _start_browser(self, task_spec: Dict[str, Any]):
        """Start Playwright browser"""
        self.playwright = sync_playwright().start()
        launch_kwargs = {
            "headless": self.headless,
            "slow_mo": self.slow_mo,
            "args": ['--no-proxy-server'],
        }
        try:
            self.browser = self.playwright.chromium.launch(**launch_kwargs)
        except Exception as e:
            # Some macOS installs resolve to a missing x64 headless-shell path.
            # Retry with an explicitly discovered local Chromium executable.
            if "Executable doesn't exist" not in str(e):
                raise
            fallback = self._find_local_chromium_executable()
            if not fallback:
                raise
            print(f"⚠️  Browser executable missing, retrying with fallback: {fallback}")
            launch_kwargs["executable_path"] = fallback
            self.browser = self.playwright.chromium.launch(**launch_kwargs)

        self.context = self.browser.new_context(
            viewport={'width': 1280, 'height': 720},
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        )
        task_id = str(task_spec.get("task_id") or "").strip()
        binding_task_id = str(
            task_spec.get("binding_task_id")
            or task_spec.get("backing_task_id")
            or task_spec.get("source_task_id")
            or task_id
        ).strip()
        init_chunks = []
        if task_id:
            init_chunks.append(f"window.__WEBAGENT_TASK_ID__ = {json.dumps(task_id)};")
        if binding_task_id:
            init_chunks.append(
                f"window.__WEBAGENT_BINDING_TASK_ID__ = {json.dumps(binding_task_id)};"
            )
        if init_chunks:
            self.context.add_init_script(script="".join(init_chunks))

        self.page = self.context.new_page()
        self.page.on("console", lambda msg: print(f"PAGE CONSOLE: {msg.text}"))

        # Keep a moderate timeout to reduce flaky navigation failures under load.
        self.page.set_default_timeout(15000)

    def _find_local_chromium_executable(self) -> Optional[str]:
        """Best-effort discovery of a local Playwright Chromium binary."""
        candidates: List[Path] = []

        cache_dir = Path.home() / "Library" / "Caches" / "ms-playwright"
        if cache_dir.exists():
            candidates.extend(cache_dir.glob("chromium_headless_shell-*/**/chrome-headless-shell"))
            candidates.extend(
                cache_dir.glob(
                    "chromium-*/**/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
                )
            )
            candidates.extend(cache_dir.glob("chromium-*/**/Chromium.app/Contents/MacOS/Chromium"))

        # Prefer native arm64 builds when available on Apple Silicon.
        def score(path: Path) -> Tuple[int, str]:
            s = str(path)
            if "arm64" in s:
                return (0, s)
            if "x64" in s:
                return (1, s)
            return (2, s)

        for candidate in sorted({p for p in candidates if p.exists() and os.access(p, os.X_OK)}, key=score):
            return str(candidate)
        return None

    def _stop_browser(self):
        """Stop browser"""
        if self.page:
            self.page.close()
        if self.context:
            self.context.close()
        if self.browser:
            self.browser.close()
        if hasattr(self, 'playwright'):
            self.playwright.stop()

    def _map_url(self, url: str) -> str:
        """Map domain URLs to localhost for testing"""
        raw = str(url or "").strip()
        if not raw:
            return raw

        parsed = urlsplit(raw)
        host = (parsed.hostname or "").lower()
        path = parsed.path or ""

        # Legacy traces often store suite URLs as
        # http://localhost:8014/shop.local/<page>. When targeted audits run on a
        # different port, those absolute URLs must be remapped to the runtime
        # server for the current episode.
        if host in {"localhost", "127.0.0.1"} and path.startswith("/"):
            domain_match = re.match(r"^/([\w.-]+\.local)(/.*)?$", path)
            if domain_match:
                domain = domain_match.group(1)
                remainder = domain_match.group(2) or ""
                return urlunsplit((
                    parsed.scheme or "http",
                    f"localhost:{self.SUITE_PORT}",
                    f"/{domain}{remainder}",
                    parsed.query,
                    parsed.fragment,
                ))

        # Also support canonical domain-style URLs such as http://shop.local/...
        if host.endswith(".local"):
            return urlunsplit((
                parsed.scheme or "http",
                f"localhost:{self.SUITE_PORT}",
                f"/{host}{path}",
                parsed.query,
                parsed.fragment,
            ))

        return raw

    def _execute_step(self, step: Dict[str, Any], task_spec: Dict[str, Any]):
        """Execute a single step"""
        action = step['act']

        if action == 'open':
            url = step['url']
            # Map domain URLs to localhost
            url = self._map_url(url)
            print(f"    → Opening {url}")
            self.page.goto(url, wait_until='networkidle')
            self._fallback_input_cursor = 0
            # Mandatory delay for distractors to block UI
            time.sleep(self.open_settle_sec)

        elif action == 'click':
            selector = step['selector']
            force = step.get('force', False)
            print(f"    → Clicking {selector} (force={force})")
            # Wait before click to ensure distractor is there
            time.sleep(self.click_pause_sec)
            try:
                sel = f"xpath={selector}" if selector.strip().startswith("//") else selector
                self.page.click(sel, force=force)
            except Exception as click_err:
                print(f"    ⚠️  Primary click failed: {click_err}")
                if not force:
                    try:
                        self.page.click(sel, force=True)
                        # Some distractor overlays still swallow pointer events at runtime.
                        # Trigger a direct DOM click to ensure onclick handlers run.
                        try:
                            self.page.eval_on_selector(sel, "el => el.click()")
                        except Exception:
                            pass
                        print("    ↪ Retried click with force=True")
                        time.sleep(1)
                        return
                    except Exception as force_err:
                        print(f"    ⚠️  Force click retry failed: {force_err}")
                try:
                    self.page.eval_on_selector(sel, "el => el.click()")
                    print("    ↪ Retried click via DOM click()")
                    time.sleep(1)
                    return
                except Exception as dom_click_err:
                    print(f"    ⚠️  DOM click retry failed: {dom_click_err}")
                fallback_selectors = []
                if not selector.strip().startswith("//"):
                    sanitized = re.sub(r":has-text\(([\"']).*?\1\)", "", selector)
                    sanitized = re.sub(r":has\(([^)(]+|\([^)(]*\))*\)", "", sanitized)
                    sanitized = re.sub(r"\s+", " ", sanitized).strip()
                    if sanitized and sanitized != selector:
                        fallback_selectors.append(sanitized)
                has_text = self._extract_has_text(selector)
                if has_text:
                    text_variants = [has_text, has_text.replace(" ", "")]
                    camel_split = re.sub(r"([a-z])([A-Z])", r"\1 \2", has_text)
                    if camel_split != has_text:
                        text_variants.append(camel_split)
                    for txt in text_variants:
                        if txt:
                            escaped = txt.replace("'", "\\'")
                            fallback_selectors.extend([
                                f"button:has-text('{escaped}')",
                                f".btn:has-text('{escaped}')",
                                f"[role='button']:has-text('{escaped}')",
                                f"text={txt}",
                            ])
                if '.modal-confirm' in selector or 'modal' in selector:
                    fallback_selectors.extend([
                        '.modal-confirm',
                        '.modal .btn.pri',
                        '.modal button.btn.pri',
                        '.modal button.btn'
                    ])
                if 'button' in selector or ':has-text(' in selector:
                    fallback_selectors.extend([
                        'button.btn.pri.lg',
                        'button.btn.pri',
                        'button.pri',
                        '.btn.pri',
                        'button.btn.ok',
                        'button.btn'
                    ])
                if selector.startswith('#'):
                    ident = selector[1:]
                    fallback_selectors.extend([
                        f"[id*='{ident.replace('-', '')}']",
                        f"[id*='{ident.split('-')[0]}']",
                    ])
                for token in self._selector_tokens(selector)[:3]:
                    fallback_selectors.extend([
                        f"[id*='{token}'] button",
                        f"[class*='{token}'] button",
                        f"[id*='{token}'] .btn.pri",
                        f"[class*='{token}'] .btn.pri",
                        f"[id*='{token}']",
                        f"[class*='{token}']",
                    ])
                fallback_selectors.extend([
                    '.modal-confirm',
                    'button.btn.pri.lg',
                    'button.btn.pri',
                    '.btn.pri',
                    'button[type=\"submit\"]'
                ])

                clicked = False
                for fb in fallback_selectors:
                    try:
                        loc = self.page.locator(fb)
                        loc_count = loc.count()
                        if loc_count == 0:
                            continue
                        for i in range(min(loc_count, 5)):
                            cand = loc.nth(i)
                            if cand.is_visible():
                                cand.click(force=force)
                                print(f"    ↪ Fallback click used: {fb}")
                                clicked = True
                                break
                        if clicked:
                            break
                    except Exception:
                        continue
                if not clicked:
                    raise
            # Wait after click for any transitions
            time.sleep(1)

        elif action == 'type':
            selector = step['selector']
            value = step['value']
            print(f"    → Typing '{value}' into {selector}")
            sel = f"xpath={selector}" if selector.strip().startswith("//") else selector
            try:
                loc = self.page.locator(sel)
                if loc.count() == 0:
                    try:
                        self.page.wait_for_selector(sel, timeout=2500)
                    except Exception:
                        pass
                    loc = self.page.locator(sel)
                if loc.count() > 0:
                    target = loc.first
                    tag_name = (target.evaluate("(el) => (el.tagName || '').toLowerCase()") or "").strip()
                    input_type = (target.get_attribute("type") or "").strip().lower()
                    role = (target.get_attribute("role") or "").strip().lower()
                    text = (target.inner_text() or "").strip()
                    value_attr = (target.get_attribute("value") or "").strip()
                    button_like = (
                        tag_name in {"button", "a", "summary"}
                        or input_type in {"button", "submit", "checkbox", "radio"}
                        or role in {"button", "checkbox", "radio", "switch", "tab"}
                    )
                    normalized_value = str(value or "").strip().lower()
                    normalized_text = text.lower()
                    normalized_attr = value_attr.lower()
                    if button_like and (
                        not normalized_value
                        or normalized_value == normalized_text
                        or normalized_value == normalized_attr
                        or normalized_value in normalized_text
                        or normalized_value in normalized_attr
                    ):
                        target.click(force=True)
                        print("    ↪ Coerced TYPE on button-like element to CLICK")
                        time.sleep(1)
                        return
                self.page.fill(sel, value)
            except Exception as type_err:
                print(f"    ⚠️  Primary type failed: {type_err}")
                try:
                    if loc.count() > 0:
                        target = loc.first
                        tag_name = (target.evaluate("(el) => (el.tagName || '').toLowerCase()") or "").strip()
                        input_type = (target.get_attribute("type") or "").strip().lower()
                        role = (target.get_attribute("role") or "").strip().lower()
                        text = (target.inner_text() or "").strip()
                        value_attr = (target.get_attribute("value") or "").strip()
                        button_like = (
                            tag_name in {"button", "a", "summary"}
                            or input_type in {"button", "submit", "checkbox", "radio"}
                            or role in {"button", "checkbox", "radio", "switch", "tab"}
                        )
                        normalized_value = str(value or "").strip().lower()
                        normalized_text = text.lower()
                        normalized_attr = value_attr.lower()
                        if button_like and (
                            not normalized_value
                            or normalized_value == normalized_text
                            or normalized_value == normalized_attr
                            or normalized_value in normalized_text
                            or normalized_value in normalized_attr
                        ):
                            target.click(force=True)
                            print("    ↪ Coerced TYPE on button-like element to CLICK")
                            time.sleep(1)
                            return
                except Exception as click_like_err:
                    print(f"    ⚠️  Button-like TYPE fallback failed: {click_like_err}")
                typed = self._fallback_fill(selector, value)
                if not typed:
                    raise

        elif action == 'select':
            selector = step['selector']
            value = step['value']
            print(f"    → Selecting '{value}' from {selector}")
            try:
                sel = f"xpath={selector}" if selector.strip().startswith("//") else selector
                self.page.select_option(sel, value)
            except Exception as select_err:
                print(f"    ⚠️  Primary select failed: {select_err}")
                if not self._fallback_select(selector, value):
                    raise

        elif action == 'wait':
            selector = step['selector']
            print(f"    → Waiting for {selector}")
            # Wait a bit for async operations
            time.sleep(1)
            try:
                sel = f"xpath={selector}" if selector.strip().startswith("//") else selector
                self.page.wait_for_selector(sel, timeout=10000)
            except Exception as wait_err:
                print(f"    ⚠️  Primary wait failed: {wait_err}")
                # If redirect/navigation succeeded, allow robust fallback wait points.
                self.page.wait_for_load_state('networkidle', timeout=10000)
                for fb in ['body', '.container', '.card', 'main']:
                    try:
                        self.page.wait_for_selector(fb, timeout=1500)
                        print(f"    ↪ Fallback wait used: {fb}")
                        break
                    except Exception:
                        continue

        elif action == 'assert':
            selector = step.get('selector')
            expected = step.get('value')
            print(f"    → Asserting {selector} == {expected}")

            # Get actual value
            if selector:
                actual = self.page.locator(selector).inner_text()

                # If no expected provided, assert element exists
                if expected is None:
                    if self.page.locator(selector).count() == 0:
                        raise AssertionError(f"{selector} not found")
                    return

                # Memory comparison mem('key')
                if isinstance(expected, str) and expected.startswith("mem('"):
                    key = expected.split("mem('",1)[1].split("')",1)[0]
                    expected_val = self.memory.get(key)
                    if str(actual).strip() != str(expected_val).strip():
                        raise AssertionError(f"Expected mem('{key}')='{expected_val}', got '{actual}'")
                    return

                # Numeric comparison like "<=30"
                if isinstance(expected, str) and str(expected).strip().startswith(('<=','>=')):
                    exp = str(expected).strip()
                    op, limit_str = exp[:2], exp[2:].strip()
                    limit = float(limit_str)
                    num_str = ''.join(ch for ch in actual if ch.isdigit() or ch == '.' or ch == '-')
                    actual_num = float(num_str) if num_str else 0.0
                    if op == '<=' and actual_num > limit:
                        raise AssertionError(f"Expected <= {limit}, got {actual_num}")
                    if op == '>=' and actual_num < limit:
                        raise AssertionError(f"Expected >= {limit}, got {actual_num}")
                else:
                    if str(actual).strip() != str(expected).strip():
                        raise AssertionError(f"Expected '{expected}', got '{actual}'")

        elif action == 'screenshot':
            screenshot_id = step.get('screenshot_id', 'screenshot')
            path = f"screenshots/{screenshot_id}.png"
            os.makedirs('screenshots', exist_ok=True)
            self.page.screenshot(path=path)
            print(f"    → Screenshot saved to {path}")

        elif action == 'verify_state':
            """Verify system state (URL, memory, DOM) instead of taking screenshot"""
            checks = step.get('checks', [])
            print(f"    → Verifying {len(checks)} state conditions")

            for check in checks:
                check_type = check.get('type')

                if check_type == 'url':
                    # Verify URL contains or matches pattern
                    if 'contains' in check:
                        expected = check['contains']
                        actual_url = self.page.url
                        if expected not in actual_url:
                            raise AssertionError(f"URL does not contain '{expected}'. Actual: {actual_url}")
                        print(f"      ✓ URL contains '{expected}'")

                    elif 'pattern' in check:
                        pattern = check['pattern']
                        actual_url = self.page.url
                        if not re.search(pattern, actual_url):
                            raise AssertionError(f"URL does not match pattern '{pattern}'. Actual: {actual_url}")
                        print(f"      ✓ URL matches pattern '{pattern}'")

                    elif 'path' in check:
                        expected_path = check['path']
                        actual_url = self.page.url
                        if expected_path not in actual_url:
                            raise AssertionError(f"URL path does not contain '{expected_path}'. Actual: {actual_url}")
                        print(f"      ✓ URL path contains '{expected_path}'")

                elif check_type == 'memory':
                    # Verify memory key exists or has specific value
                    key = check.get('key')

                    if 'exists' in check:
                        should_exist = check['exists']
                        exists = key in self.memory
                        if should_exist and not exists:
                            raise AssertionError(f"Memory key '{key}' does not exist")
                        if not should_exist and exists:
                            raise AssertionError(f"Memory key '{key}' should not exist")
                        print(f"      ✓ Memory key '{key}' existence: {should_exist}")

                    elif 'value' in check:
                        expected = check['value']
                        actual = self.memory.get(key)
                        if str(actual) != str(expected):
                            raise AssertionError(f"Memory['{key}'] = '{actual}', expected '{expected}'")
                        print(f"      ✓ Memory['{key}'] = '{expected}'")

                    elif 'not_empty' in check:
                        actual = self.memory.get(key)
                        if not actual or actual == '':
                            raise AssertionError(f"Memory key '{key}' is empty")
                        print(f"      ✓ Memory['{key}'] is not empty")

                elif check_type == 'dom':
                    # Verify DOM element exists or has specific state
                    selector = check.get('selector')

                    if 'exists' in check:
                        should_exist = check['exists']
                        count = self.page.locator(selector).count()
                        exists = count > 0
                        if should_exist and not exists:
                            raise AssertionError(f"Element '{selector}' not found")
                        if not should_exist and exists:
                            raise AssertionError(f"Element '{selector}' should not exist")
                        print(f"      ✓ Element '{selector}' existence: {should_exist}")

                    elif 'count' in check:
                        expected_count = check['count']
                        actual_count = self.page.locator(selector).count()
                        if actual_count != expected_count:
                            raise AssertionError(f"Element '{selector}' count: {actual_count}, expected {expected_count}")
                        print(f"      ✓ Element '{selector}' count: {expected_count}")

                    elif 'text_contains' in check:
                        expected_text = check['text_contains']
                        actual_text = self.page.locator(selector).inner_text()
                        if expected_text not in actual_text:
                            raise AssertionError(f"Element '{selector}' text does not contain '{expected_text}'")
                        print(f"      ✓ Element '{selector}' contains text '{expected_text}'")

                    elif 'not_empty' in check:
                        # Check if element has non-empty text content
                        text = self.page.locator(selector).inner_text().strip()
                        if not text:
                            raise AssertionError(f"Element '{selector}' is empty")
                        print(f"      ✓ Element '{selector}' has content: '{text[:50]}...'")


            # Optional: take screenshot as backup if specified
            if step.get('screenshot_fallback'):
                screenshot_id = step.get('screenshot_id', 'verify_state')
                path = f"screenshots/{screenshot_id}.png"
                os.makedirs('screenshots', exist_ok=True)
                self.page.screenshot(path=path)
                print(f"      📸 Backup screenshot: {path}")

        elif action == 'verify_dom':
            """Verify multiple DOM selectors exist"""
            selectors = step.get('selectors', [])
            print(f"    → Verifying {len(selectors)} DOM elements")

            for selector in selectors:
                count = self.page.locator(selector).count()
                if count == 0:
                    raise AssertionError(f"Element '{selector}' not found")
                print(f"      ✓ Element '{selector}' exists")

        elif action == 'verify_memory':
            """Verify memory state"""
            key = step.get('key')

            if 'exists' in step:
                should_exist = step['exists']
                exists = key in self.memory
                if should_exist and not exists:
                    raise AssertionError(f"Memory key '{key}' does not exist")
                if not should_exist and exists:
                    raise AssertionError(f"Memory key '{key}' should not exist")
                print(f"    → Memory key '{key}' existence verified: {should_exist}")

            elif 'value' in step:
                expected = step['value']
                actual = self.memory.get(key)
                if str(actual) != str(expected):
                    raise AssertionError(f"Memory['{key}'] = '{actual}', expected '{expected}'")
                print(f"    → Memory['{key}'] = '{expected}' ✓")

        elif action == 'upload':
            selector = step['selector']
            filepath = step['value']
            print(f"    → Uploading {filepath} to {selector}")
            self.page.set_input_files(selector, filepath)

        elif action == 'download':
            # Start waiting for download
            with self.page.expect_download() as download_info:
                self.page.click(step['selector'])
            download = download_info.value

            # Save to downloads directory
            filename = step.get('value', download.suggested_filename)
            os.makedirs('downloads', exist_ok=True)
            download.save_as(f"downloads/{filename}")
            print(f"    → Downloaded {filename}")

        elif action == 'extract':
            variable_name = step['variable']
            value = step.get('value')

            if value is None:
                selector = step['selector']
                try:
                    text = self.page.locator(selector).inner_text().strip()
                    # Try to convert to number if possible (basic heuristic)
                    # Remove currency symbols and commas
                    clean_text = re.sub(r'[^\d.-]', '', text)
                    try:
                        value = float(clean_text) if '.' in clean_text else int(clean_text)
                    except ValueError:
                        value = text
                    print(f"    → Extracted '{variable_name}' = {value} from {selector}")
                except Exception as e:
                    print(f"    ⚠️  Failed to extract from {selector}: {e}")
                    return
            else:
                print(f"    → Using provided value for '{variable_name}' = {value}")
            
            # Update memory
            self._save_memory(variable_name, value, 'extraction')
            
            # Update extracted data
            if not hasattr(self, '_extracted_data'):
                self._extracted_data = {}
            self._extracted_data[variable_name] = value

        else:
            print(f"    ⚠️  Unknown action: {action}")

        # Post-step settlement delay
        time.sleep(1.0)

    def _handle_step_error(
        self,
        error: Exception,
        step: Dict[str, Any],
        task_spec: Dict[str, Any],
        step_index: int
    ) -> ErrorReport:
        """Handle step execution error"""

        error_type = type(error).__name__

        # Create error report
        error_report = ErrorReport(
            task_id=task_spec['task_id'],
            error_type=error_type,
            timestamp=datetime.utcnow().isoformat() + "Z",
            step_index=step_index,
            error_message=str(error),
            step=step,
            context={
                "url": self.page.url if self.page else None
            }
        )

        # Try to capture screenshot
        try:
            screenshot_path = f"errors/{task_spec['task_id']}/error_step_{step_index}.png"
            os.makedirs(os.path.dirname(screenshot_path), exist_ok=True)
            if self.page:
                print(f"    ❌ Error URL: {self.page.url}")
                self.page.screenshot(path=screenshot_path)
                error_report.context['screenshot'] = screenshot_path
        except:
            pass

        # Apply error recovery strategy
        recovery = task_spec.get('error_recovery', {})

        if 'timeout' in error_type.lower():
            strategy = recovery.get('on_timeout', 'capture_state_and_abort')
            if strategy == 'capture_state_and_abort':
                error_report.final_state = 'aborted'

        # Save error report
        error_report.save(f"errors/{task_spec['task_id']}")

        return error_report

    def _verify_success(self, task_spec: Dict[str, Any]) -> bool:
        """Verify task success criteria and required scoring checkpoints."""
        success_criteria = task_spec.get('success_criteria', [])
        scoring_checkpoints = task_spec.get('scoring_checkpoints', [])

        self._last_verification = {
            "success": False,
            "criteria_ok": True,
            "checkpoints_ok": True,
            "criteria_total": 0,
            "criteria_passed": 0,
            "criteria_failed": [],
            "checkpoint_total": 0,
            "checkpoint_passed": 0,
            "required_failed": [],
            "required_failed_ids": [],
            "step_progress": 0.0,
            "step_score_percent": 0.0,
        }

        if not success_criteria and not scoring_checkpoints:
            self._last_verification.update(
                {
                    "success": True,
                    "step_progress": 1.0,
                    "step_score_percent": 100.0,
                }
            )
            return True

        # Refresh memory from DB to include runtime updates (e.g., new orders)
        self._load_memory()

        # Create DSL evaluator
        self.dsl = AssertionDSL(self.page, self.memory, self._env_api)

        criteria_ok = True
        criteria_failed: List[str] = []
        for criterion in success_criteria:
            try:
                result = self.dsl.evaluate(criterion)
                if not result:
                    print(f"    ❌ Criterion failed: {criterion}")
                    criteria_ok = False
                    criteria_failed.append(str(criterion))
                else:
                    print(f"    ✅ Criterion passed: {criterion[:80]}...")
            except Exception as e:
                print(f"    ❌ Criterion error: {e}")
                criteria_ok = False
                criteria_failed.append(str(criterion))

        criteria_total = len(success_criteria)
        criteria_passed = max(0, criteria_total - len(criteria_failed))

        checkpoints: List[Dict[str, Any]] = []
        if isinstance(scoring_checkpoints, list) and scoring_checkpoints:
            used_ids = set()
            for i, raw_cp in enumerate(scoring_checkpoints):
                if isinstance(raw_cp, str):
                    cp = {
                        "id": f"cp_{i+1}",
                        "name": f"Checkpoint {i+1}",
                        "assertion": str(raw_cp),
                        "required": True,
                        "depends_on": [],
                        "when": "",
                    }
                elif isinstance(raw_cp, dict):
                    assertion = str(raw_cp.get("assertion", "")).strip()
                    if not assertion:
                        continue
                    cp = {
                        "id": str(raw_cp.get("id", f"cp_{i+1}")).strip() or f"cp_{i+1}",
                        "name": str(raw_cp.get("name", f"Checkpoint {i+1}")),
                        "assertion": assertion,
                        "required": bool(raw_cp.get("required", True)),
                        "depends_on": raw_cp.get("depends_on", []),
                        "when": str(raw_cp.get("when", "")).strip(),
                    }
                else:
                    continue

                cp_id = cp["id"]
                if cp_id in used_ids:
                    cp["id"] = f"{cp_id}_{i+1}"
                used_ids.add(cp["id"])

                depends_on = cp.get("depends_on", [])
                if isinstance(depends_on, str):
                    depends_on = [depends_on]
                if not isinstance(depends_on, list):
                    depends_on = []
                cp["depends_on"] = [str(d).strip() for d in depends_on if str(d).strip()]
                checkpoints.append(cp)

        checkpoints_ok = True
        checkpoint_total = 0
        checkpoint_passed = 0
        step_progress = (float(criteria_passed) / float(criteria_total)) if criteria_total else 1.0
        step_score_percent = step_progress * 100.0
        required_failed_assertions: List[str] = []
        required_failed_ids: List[str] = []

        if checkpoints:
            print("    → Verifying required checkpoints...")
            activation_map: Dict[str, bool] = {}
            active_checkpoints: List[Dict[str, Any]] = []
            for cp in checkpoints:
                cp_id = cp["id"]
                when_expr = str(cp.get("when", "")).strip()
                is_active = True
                if when_expr:
                    try:
                        is_active = bool(self.dsl.evaluate(when_expr))
                    except Exception:
                        is_active = False
                activation_map[cp_id] = is_active
                if is_active:
                    active_checkpoints.append(cp)
                else:
                    print(f"    ⏭ Checkpoint skipped (inactive): {cp_id}")

            if not active_checkpoints:
                print("    ❌ No active checkpoint branch")
                checkpoints_ok = False
                required_failed_ids = ["NO_ACTIVE_CHECKPOINT_BRANCH"]
                required_failed_assertions = ["NO_ACTIVE_CHECKPOINT_BRANCH"]
            else:
                total_weight = 0.0
                for cp in active_checkpoints:
                    try:
                        w = float(cp.get("weight", 1.0))
                    except Exception:
                        w = 1.0
                    if w < 0:
                        w = 0.0
                    cp["weight"] = w
                    total_weight += w
                if total_weight <= 0:
                    for cp in active_checkpoints:
                        cp["weight_norm"] = 1.0 / len(active_checkpoints)
                else:
                    for cp in active_checkpoints:
                        cp["weight_norm"] = float(cp.get("weight", 0.0)) / total_weight

                raw_pass_map: Dict[str, bool] = {}
                for cp in active_checkpoints:
                    cp_id = cp["id"]
                    assertion = cp.get("assertion", "")
                    try:
                        raw_pass_map[cp_id] = bool(self.dsl.evaluate(assertion))
                    except Exception as e:
                        print(f"    ❌ Checkpoint eval error ({cp_id}): {e}")
                        raw_pass_map[cp_id] = False

                final_pass_map: Dict[str, bool] = {}
                required_failed: List[str] = []
                earned = 0.0
                for cp in active_checkpoints:
                    cp_id = cp["id"]
                    depends_on = cp.get("depends_on", [])
                    deps_ok = all(final_pass_map.get(dep, False) for dep in depends_on)
                    cp_ok = bool(raw_pass_map.get(cp_id, False)) and deps_ok
                    final_pass_map[cp_id] = cp_ok

                    mark = "✅" if cp_ok else "❌"
                    print(f"    {mark} Checkpoint {cp_id}: {cp.get('assertion', '')}")
                    if cp_ok:
                        earned += float(cp.get("weight_norm", 0.0))
                    if bool(cp.get("required", True)) and not cp_ok:
                        required_failed.append(cp_id)
                        required_failed_assertions.append(str(cp.get("assertion", "")))

                checkpoint_total = len(active_checkpoints)
                checkpoint_passed = sum(1 for cp in active_checkpoints if final_pass_map.get(cp.get("id"), False))
                step_progress = max(0.0, min(1.0, earned))
                step_score_percent = step_progress * 100.0

                if required_failed:
                    print(f"    ❌ Required checkpoints failed: {', '.join(required_failed)}")
                    checkpoints_ok = False
                    required_failed_ids = list(required_failed)

        if checkpoints:
            self._last_verification.update(
                {
                    "criteria_total": checkpoint_total,
                    "criteria_passed": checkpoint_passed,
                    "criteria_failed": list(required_failed_assertions),
                    "checkpoint_total": checkpoint_total,
                    "checkpoint_passed": checkpoint_passed,
                }
            )
        else:
            self._last_verification.update(
                {
                    "criteria_total": criteria_total,
                    "criteria_passed": criteria_passed,
                    "criteria_failed": list(criteria_failed),
                    "checkpoint_total": 0,
                    "checkpoint_passed": 0,
                }
            )

        success = bool(criteria_ok) and bool(checkpoints_ok)
        self._last_verification.update(
            {
                "success": success,
                "criteria_ok": bool(criteria_ok),
                "checkpoints_ok": bool(checkpoints_ok),
                "required_failed": list(required_failed_assertions),
                "required_failed_ids": list(required_failed_ids),
                "step_progress": float(step_progress),
                "step_score_percent": float(step_score_percent),
            }
        )

        return success

    def _update_memory(self, task_spec: Dict[str, Any]):
        """Update memory based on task execution"""
        memory_keys = task_spec.get('memory_keys', [])

        print(f"\n💾 Updating {len(memory_keys)} memory entries...")

        # Load expected memory if available
        task_dir = Path(task_spec.get('_path', '.')).parent
        expected_memory_path = Path(task_dir) / 'expected_memory.json'

        if expected_memory_path.exists():
            with open(expected_memory_path) as f:
                expected_memory = json.load(f)

            for key, entry in expected_memory.items():
                value = entry.get('value')
                source = entry.get('source', task_spec['task_id'])
                confidence = entry.get('confidence', 1.0)

                self._save_memory(key, value, source, confidence)
                print(f"  ✅ {key} = {value}")

    def _save_result(self, result: ExecutionResult):
        """Save execution result to database with retry logic"""
        if not os.path.exists(self.database_path):
            return

        for attempt in range(5):
            try:
                conn = sqlite3.connect(self.database_path, timeout=10)
                cursor = conn.cursor()

                cursor.execute("""
                    INSERT INTO task_executions (
                        task_id, agent_version, state, started_at, completed_at,
                        error_type, error_message, steps_completed, steps_total
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    result.task_id,
                    "executor-v1.0.0",
                    result.final_state,
                    datetime.utcnow().isoformat(),
                    datetime.utcnow().isoformat(),
                    result.error.error_type if result.error else None,
                    result.error.error_message if result.error else None,
                    result.steps_completed,
                    result.steps_total
                ))

                conn.commit()
                conn.close()

                print(f"✅ Execution result saved to database")
                return
            except sqlite3.OperationalError as e:
                if "locked" in str(e):
                    print(f"⚠️  Database locked saving result, retrying ({attempt+1}/5)...")
                    time.sleep(1)
                else:
                    print(f"⚠️  Error saving result: {e}")
                    return
            except Exception as e:
                print(f"⚠️  Error saving result: {e}")
                return


# Convenience function
def execute_task(task_spec_path: str, oracle_trace_path: Optional[str] = None, **kwargs) -> ExecutionResult:
    """
    Execute a task (convenience function)

    Args:
        task_spec_path: Path to task_spec.json
        oracle_trace_path: Optional path to oracle_trace.json
        **kwargs: Additional arguments for TaskExecutor

    Returns:
        ExecutionResult
    """
    executor = TaskExecutor(**kwargs)
    return executor.run(task_spec_path, oracle_trace_path)


if __name__ == "__main__":
    # Example usage
    import sys

    if len(sys.argv) < 2:
        print("Usage: python executor.py <task_spec.json> [oracle_trace.json]")
        sys.exit(1)

    task_spec = sys.argv[1]
    oracle_trace = sys.argv[2] if len(sys.argv) > 2 else None

    result = execute_task(task_spec, oracle_trace, headless=False, slow_mo=500)

    print("\n" + "="*80)
    print("FINAL RESULT")
    print("="*80)
    print(json.dumps(result.to_dict(), indent=2))
